(deftheme monokai_custom
  "Created 2014-11-03.")

(custom-theme-set-faces
 'monokai_custom
 '(default ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :height 105 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#DFDFD9" :background "#272822" :stipple nil :inherit nil))))
 '(cursor ((t (:inverse-video t :foreground "#272822" :background "#F8F8F2"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#AE81FF"))))
 '(minibuffer-prompt ((t (:foreground "#66D9EF"))))
 '(highlight ((t (:background "#49483E"))))
 '(region ((t (:background "#49483E" :inherit (t)))))
 '(shadow ((t (:foreground "#888888"))))
 '(secondary-selection ((t (:background "#49483E" :inherit (t)))))
 '(trailing-whitespace ((t (:background "#F92672"))))
 '(font-lock-builtin-face ((t (:weight normal :foreground "#F92672"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face :foreground "#888888"))))
 '(font-lock-comment-face ((t (:foreground "#888888"))))
 '(font-lock-constant-face ((t (:foreground "#AE81FF"))))
 '(font-lock-doc-face ((t (:inherit font-lock-string-face :foreground "#888888"))))
 '(font-lock-function-name-face ((t (:foreground "#A6E22E"))))
 '(font-lock-keyword-face ((t (:weight normal :foreground "#F92672"))))
 '(font-lock-negation-char-face ((t (:weight bold :foreground "#E6DB74"))))
 '(font-lock-preprocessor-face ((t (:foreground "#F92672" :inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:weight normal :foreground "#AE81FF" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:weight normal :foreground "#E6DB74" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#E6DB74"))))
 '(font-lock-type-face ((t (:slant italic :foreground "#66D9EF"))))
 '(font-lock-variable-name-face ((t (:foreground "#FD971F"))))
 '(font-lock-warning-face ((t (:weight bold :slant italic :underline (:color foreground-color :style line) :foreground "#FD971F" :inherit (error)))))
 '(button ((t (:underline (:color foreground-color :style line) :inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#66D9EF"))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#66D9EF" :inherit (link)))))
 '(fringe ((t (:foreground "#F8F8F2" :background "#272822"))))
 '(header-line ((t (:box (:line-width 1 :color "#49483E" :style unspecified) :foreground "#F8F8F0" :background "#49483E" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "#F3EA98" :background "#968B26" :inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width 1 :color "#3E3D31" :style unspecified) :foreground "#F8F8F2" :background "#3E3D31"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#A6E22E"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:weight light :box (:line-width 1 :color "#3E3D31" :style unspecified) :foreground "#75715E" :background "#272822" :inherit (mode-line)))))
 '(isearch ((t (:weight normal :foreground "#272822" :background "#FD5FF0"))))
 '(isearch-fail ((t (:weight bold :foreground "#F92672" :background "#272822"))))
 '(lazy-highlight ((t (:weight normal :foreground "#272822" :background "#E6DB74"))))
 '(match ((t (:weight bold :foreground "#F8F8F0" :background "#49483E"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'monokai_custom)
